RL\ImmoCrawlerBundle\Entity\Property:
    type: entity
    table: null
    repositoryClass: RL\ImmoCrawlerBundle\Entity\PropertyRepository
    fields:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
        title:
            type: string
            length: 255
        description:
            type: text
        area:
            type: smallint
        price:
            type: integer
        type:
            type: string
            length: 255
        rooms:
            type: smallint
        energyClass:
            type: string
            length: 255
            column: energy_class
        ges:
            type: string
            length: 255
        city:
            type: string
            length: 255
        zipcode:
            type: string
            length: 255
        street:
            type: string
            length: 255
    lifecycleCallbacks: {  }
